version: '3'
services:
  server:
    image: server
    ports:
      - "5000:5000"      
    # deploy:
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    # networks:
    #   - webnet
  client:
    image: client
    ports:
      - "3000:3000"    
    # deploy:
    #   replicas: 2
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    environment:
      - EFFICIENT_URL=http://0.0.0.0
    # networks:
    #   - webnet
  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
    # networks:
    #   - webnet
# networks:
#   webnet:

    

