version: '3'
services:
  server:
    image: docker/server
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure        
  client:
    image: docker/client
    command: npm run serve
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure


    

